### ISSUE TITLE
Issues with buttons

### ISSUE THREAD

**Issue by Collcroc123** [rose-pine/steam-os#10]
Let me start out by saying I love this theme, it just looks so nice and sleek, it's so much better than the base Steam OS.
That said I did notice at least 2 issues that make navigating more difficult:
- The first is that when you hover over buttons or drop down menus with text, instead of the button turning white and the text dimming, the text just dims and the button stays the same, making the text nearly unreadable. You really have to squint to read it.
![image](https://user-images.githubusercontent.com/32398853/195016982-219c1327-30b5-4bea-bb26-12573a821c09.png)

- The other issue is when you select a game, the play button is no longer green when it's highlighted, it just stays the same color whether or not you highlight it, so I can never tell where my cursor is and whether or not it's already hovering over the play button.
![image](https://user-images.githubusercontent.com/32398853/195017028-4e601b92-a63c-49ec-8808-8b7eb9332c7d.png)

I really hope those two things are tweaked/changed/fixed, please keep up the good work!

**Comment by mtb0w** [comment]
+1 to @Collcroc123 . These 2 issues are the only thing holding this back from perfection. A fix would be appreciated 🙏
